#ifndef INTERFACE_PLUGIN_GLOBAL_H
#define INTERFACE_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTERFACE_PLUGIN_LIBRARY)
#define INTERFACE_PLUGIN_SHARED_EXPORT Q_DECL_EXPORT
#else
#define INTERFACE_PLUGIN_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INTERFACE_PLUGIN_GLOBAL_H
